#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_USE_DEV_VERSION
#define LV_COLOR_DEPTH 16
#define LV_COLOR_16_SWAP 0

#define LV_MEM_CUSTOM 1
#define LV_MEM_SIZE (16 * 1024U)

#define LV_USE_LOG 1
#if LV_USE_LOG
    #define LV_LOG_LEVEL LV_LOG_LEVEL_WARN
    #define LV_LOG_PRINTF 1
#endif

#define LV_FONT_MONTSERRAT_12 1
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_16 1
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_MONTSERRAT_24 1
#define LV_FONT_MONTSERRAT_28 0
#define LV_FONT_MONTSERRAT_32 0
#define LV_FONT_MONTSERRAT_48 0

#define LV_USE_THEME_DEFAULT 1
#define LV_THEME_DEFAULT_DARK 0

#define LV_USE_BTN 1
#define LV_USE_LABEL 1
#define LV_USE_TEXTAREA 1
#define LV_USE_KEYBOARD 1
#define LV_USE_BAR 1
#define LV_USE_SLIDER 1
#define LV_USE_DROPDOWN 1
#define LV_USE_SPINNER 1
#define LV_USE_ARC 1

#define LV_TICK_CUSTOM 1
#define LV_DISP_DEF_REFR_PERIOD 50

#endif
